version: 2

references:
  workspace_root: &workspace_root
    ~/workspace

  working_directory: &working_directory
    ~/workspace/code

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  node_container: &node_container
    docker:
      - image: circleci/node:10.15.3-stretch
    working_directory: *working_directory

  awscli_container: &awscli_container
    docker:
      - image: zackijack/circleci-awscli:1.16.125
    working_directory: *working_directory

jobs:
  build:
    <<: *node_container
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Cache
          keys:
            - v1-yarn-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-yarn-{{ arch }}-{{ .Branch }}-
            - v1-yarn-{{ arch }}-
      - restore_cache:
          name: Restore node_modules Cache
          keys:
            - v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-node-{{ arch }}-{{ .Branch }}-
            - v1-node-{{ arch }}-
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Cache
          key: v1-yarn-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          name: Save node_modules Cache
          key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - code

  test-unit:
    <<: *node_container
    steps:
      - *attach_workspace
      - run:
          name: Unit Test
          command: yarn test:unit

  deploy:
    <<: *awscli_container
    steps:
      - *attach_workspace
      - run:
          name: Install AWS CLI
          command: sudo pip install awscli
      - run:
          name: Deploy to AWS S3
          command: aws s3 sync --acl public-read --cache-control max-age=86400 --delete dist/ s3://$AWS_S3_BUCKET_NAME
      - run:
          name: Create Invalidation in AWS CloudFront
          command: aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths '/*'

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test-unit:
          requires:
            - build
      - deploy:
          requires:
            - test-unit
          filters:
            branches:
              only: master
