version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.13.0-stretch
    working_directory: ~/code
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ~/.cache/yarn
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths: 
            - dist/**

  deploy:
    docker:
      - image: circleci/python:3-7-1-stretch
    working_directory: ~/code
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install AWS CLI
          command: sudo pip install awscli
      - run:
          name: Deploy to AWS S3
          command: aws s3 sync --acl public-read --cache-control max-age=86400 --delete dist/ s3://$AWS_S3_BUCKET_NAME
      - run:
          name: Create Invalidation in AWS CloudFront
          command: aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths '/*'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master