version: 2
jobs:
  deploy:
    docker:
      - image: circleci/python:3.7.1-stretch
    working_directory: ~/circleci-docs
    steps:
      - run:
          name: Install AWS CLI
          command: sudo pip install awscli
      - run:
          name: Deploy to S3
          command: aws s3 sync --acl public-read --cache-control max-age=86400 --delete . s3://$AWS_S3_BUCKET_NAME

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master