version: 2
jobs:
  deploy:
    docker:
      - image: circleci/python:3.7.1-stretch
    working_directory: ~/code
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: sudo pip install awscli
      - run:
          name: Deploy to AWS S3
          command: aws s3 sync --acl public-read --cache-control max-age=86400 --delete build/ s3://$AWS_S3_BUCKET_NAME
      - run:
          name: Create invalidation in AWS CloudFront
          command: aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths '/*'

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master